pipeline {
    agent any

    environment {
        BACKEND_IMAGE  = "todo-backend"
        FRONTEND_IMAGE = "todo-frontend"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Pulling latest code from GitHub...'
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                echo 'Building Flask backend Docker image...'
                bat 'docker build -t %BACKEND_IMAGE% todo-app/backend'
            }
        }

        stage('Build Frontend') {
            steps {
                echo 'Building React frontend Docker image...'
                bat 'docker build -t %FRONTEND_IMAGE% todo-app/frontend'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo 'Pushing images to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'taimourarshad123', passwordVariable: 'SazzySoda2412!')]) {
                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                    bat 'docker tag %BACKEND_IMAGE% %DOCKER_USER%/%BACKEND_IMAGE%:latest'
                    bat 'docker tag %FRONTEND_IMAGE% %DOCKER_USER%/%FRONTEND_IMAGE%:latest'
                    bat 'docker push %DOCKER_USER%/%BACKEND_IMAGE%:latest'
                    bat 'docker push %DOCKER_USER%/%FRONTEND_IMAGE%:latest'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Stopping old containers and deploying new ones...'
                bat 'docker-compose -f todo-app/docker-compose.yml down || exit 0'
                bat 'docker-compose -f todo-app/docker-compose.yml up -d'
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded! App is running.'
        }
        failure {
            echo 'Pipeline failed. Check the logs above.'
        }
    }
}